# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title test c++
#' @param x an integer
#' @export
testcpp <- function(x) {
    .Call('_safir2_testcpp', PACKAGE = 'safir2', x)
}

make_get_contact_matrix_rcpp <- function(parameters) {
    .Call('_safir2_make_get_contact_matrix_rcpp', PACKAGE = 'safir2', parameters)
}

eval_get_contact_matrix_rcpp <- function(func, timestep) {
    .Call('_safir2_eval_get_contact_matrix_rcpp', PACKAGE = 'safir2', func, timestep)
}

make_get_vector_rcpp <- function(parameters, name) {
    .Call('_safir2_make_get_vector_rcpp', PACKAGE = 'safir2', parameters, name)
}

eval_get_vector_fn_rcpp <- function(func, timestep) {
    .Call('_safir2_eval_get_vector_fn_rcpp', PACKAGE = 'safir2', func, timestep)
}

make_get_age_probabilities_rcpp <- function(parameters, name) {
    .Call('_safir2_make_get_age_probabilities_rcpp', PACKAGE = 'safir2', parameters, name)
}

eval_get_age_probabilities_fn_rcpp <- function(func, timestep, ages) {
    .Call('_safir2_eval_get_age_probabilities_fn_rcpp', PACKAGE = 'safir2', func, timestep, ages)
}

